fragment Post on PostModel {
    id
    title
    type
    publishDate
    emoji
    contentPath
}

query PostIndexPage {
  articles: posts(type: ["article"]) {
    ...Post
  }
  diaries: posts(type: ["diary"]) {
    ...Post
  }
}

query PostDetailPage($contentPath: String) {
  post: findPost(contentPath: $contentPath) {
    contentPath
    title
    publishDate
    bodyMarkdown
  }
}